[package]
name = "ssi-vc"
version = "0.2.0"
edition = "2021"
authors = ["Spruce Systems, Inc."]
license = "Apache-2.0"
description = "Verifiable Credentials Data Model v1.1 implementation for the `ssi` library."
repository = "https://github.com/spruceid/ssi/"
documentation = "https://docs.rs/ssi-vc/"

[dependencies]
ssi-crypto.workspace = true
ssi-verification-methods.workspace = true
ssi-rdf.workspace = true
ssi-security.workspace = true
treeldr-rust-macros.workspace = true
treeldr-rust-prelude.workspace = true
json-ld.workspace = true
rdf-types.workspace = true
iref.workspace = true
static-iref.workspace = true
async-trait.workspace = true
chrono.workspace = true
thiserror.workspace = true
serde = { workspace = true, features = ["derive"] }
